config/routes.rb
Disseminate::Application.routes.draw do
  resources :groups do
    resources :services do
      collection do
        get 'new/:type', action: :new_type, as: :new_type
      end
    end
  end

  match "/auth/:provider/callback" => "sessions#create", via: %i(get post)
  match '/auth/failure' => 'sessions#failure', via: %i(get post)
  match '/logout' => 'sessions#destroy', via: %i(get delete), as: :logout
  get '/sessions/new'
  root to: "root#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :user
  has_many :services

  validates :name, presence: true
end

app/models/mailing_list_service.rb
class MailingListService < Service
  store_accessor :data, :email_address
end

app/models/service.rb
class Service < ActiveRecord::Base
  TYPES = %w(
    MailingListService
  )
  belongs_to :group

  store :data

  def self.display_name
    self.model_name.to_s.demodulize.sub('Service', '')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :groups

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
      user.email = auth["info"]["email"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  # Verify that controller actions are authorized. Optional, but good.
  # after_filter :verify_authorized, except: :index
  # after_filter :verify_policy_scoped, only: :index

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :current_user

  helper_method :logged_in?
  helper_method :current_user

  protected
  def current_user
    @current_user ||= User.find(session[:user_id]) if session.has_key?(:user_id)
  rescue ActiveRecord::RecordNotFound
    session[:user_id] = nil
  end

  def current_user?
    !!current_user
  end

  def logged_in?
    current_user?
  end

  def authenticate_user!
    if session[:user_id].present?
      current_user
    else
      redirect_to redirect_path
    end
  end

  def logout!
    @current_user = nil
    reset_session
  end

  def redirect_path
    :root
  end

  def user_not_authorized
    flash[:error] = "You are not authorized to perform this action."
    redirect_to request.headers["Referer"] || root_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  respond_to :html, :json

  # GET /groups
  # GET /groups.json
  def index
    @groups = policy_scope(Group)
    respond_with @groups
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    respond_with @group
  end

  # GET /groups/new
  def new
    @group = Group.new
    respond_with @group
  end

  # GET /groups/1/edit
  def edit
    respond_with @group
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_user.groups.build(group_params)
    flash[:notice] = 'Group was successfully created.' if @group.save
    respond_with @group
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    flash[:notice] = 'Group was successfully updated.' if @group.update(group_params)
    respond_with @group
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_with @group
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
      authorize @group
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description)
    end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
    redirect_to groups_path if logged_in?
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :set_group

  respond_to :html, :json

  # GET /services
  # GET /services.json
  def index
    @services = Service.all
    respond_with @services
  end

  # GET /services/1
  # GET /services/1.json
  def show
    respond_with @service
  end

  # GET /services/new
  def new
    respond_with @service
  end

  def new_type
    @service = "#{params[:type]}_service".classify.constantize.new
  end

  # GET /services/1/edit
  def edit
    respond_with @service
  end

  # POST /services
  # POST /services.json
  def create
    @service = @group.services.build(service_params)
    flash[:notice] = 'Service was successfully created.' if @service.save
    respond_with [@group, @service.becomes(Service)] do |format|
      format.json { render :show, status: :created }
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    flash[:notice] = 'Service was successfully updated.' if @service.update(service_params)
    respond_with [@group, @service.becomes(Service)]
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to group_services_url(@group) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    def set_group
      @group = Group.find(params[:group_id])
      authorize @group, :edit?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:type, :data, :email_address)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def new; end

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def failure
    flash[:error] = I18n.t('notifications.authentication_error')
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.erb
<%= simple_form_for(@group, html: {class: 'form-horizontal' }) do |form| %>
  <%= form.error_notification %>

  <div class="form-inputs">
    <%= form.input :name %>
    <%= form.input :description %>
  </div>

  <div class="form-actions">
    <%= form.button :submit, class: 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                groups_path, :class => 'btn' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/index.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table id="groups" class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.id, group_path(group) %></td>
        <td><%= group.name %></td>
        <td><%= group.description %></td>
        <td><%=l group.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_group_path(group), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      group_path(group),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_group_path,
            :class => 'btn btn-primary' %>

app/views/groups/new.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/show.html.erb
<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @group.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @group.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              groups_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_group_path(@group), :class => 'btn' %>
  <%= link_to t('.add_service'),
              new_group_service_path(@group), class: 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              group_path(@group),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Disseminate" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="<%= root_path %>">Disseminate</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <!--
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
              -->
            </ul>
            <ul class="nav pull-right">
              <li>
                <% if logged_in? %>
                  <%= link_to t('auth.logout'), logout_path %>
                <% else %>
                  <%= link_to t('auth.login'), sessions_new_path %>
                <% end %>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <!--
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
              -->
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p class="text-center">&copy; Disseminate 2013</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/root/index.html.erb
Hello World

app/views/services/_form.html.erb
<%= simple_form_for([@group, @service.becomes(Service)]) do |f| %>
  <% f.object = @service.becomes(@service.class) %>
  <%= f.error_notification %>

  <%= f.hidden_field :type %>

  <%= render @service.type.underscore, f: f %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/services/_mailing_list_service.html.erb
  <div class="form-inputs">
    <%= f.input :email_address %>
  </div>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render 'form' %>

<%= link_to 'Show', [@group, @service.becomes(Service)] %> |
<%= link_to 'Back', group_path(@group) %>

app/views/services/index.html.erb
<h1>Listing services</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Data</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.type %></td>
        <td><%= service.data %></td>
        <td><%= link_to 'Show', [@group, service.becomes(Service)] %></td>
        <td><%= link_to 'Edit', edit_group_service_path(@group, service) %></td>
        <td><%= link_to 'Destroy', [@group, service.becomes(Service)], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service', new_group_service_path(@group) %>

app/views/services/new.html.erb
<h1>New service</h1>

<div class="services">
  <% Service::TYPES.each do |type| %>
    <%= link_to type.constantize.display_name.titleize, new_type_group_services_path(@group, type.constantize.display_name.underscore) %>
  <% end %>
</div>

app/views/services/new_type.html.erb
<%= render 'form' %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @service.type %>
</p>

<p>
  <strong>Data:</strong>
  <%= @service.data %>
</p>

<%= link_to 'Edit', edit_group_service_path(@group, @service) %> |
<%= link_to 'Back', group_path(@group) %>